-- Route Aliases: map Zwift API event-only route IDs to canonical DB route IDs
-- 
-- Zwift uses different internal route IDs for the same physical route depending
-- on context (event-only vs free-ride). This table bridges the gap so events
-- using the "other" ID still get matched to our route data.
--
-- Generated by cross-referencing:
--   1. unknown_routes table (API route_ids that failed lookup)
--   2. zwift-offline export (maps route_id → route name)
--   3. routes table (maps route name → canonical route_id)
--
-- Created: 2026-03-15

-- Ensure the table exists
CREATE TABLE IF NOT EXISTS route_aliases (
    alias_route_id INTEGER PRIMARY KEY,
    canonical_route_id INTEGER NOT NULL,
    notes TEXT,
    FOREIGN KEY (canonical_route_id) REFERENCES routes(route_id)
);

-- Aliases derived from zwift-offline export cross-reference
-- Format: (API event route_id, DB canonical route_id, description)
INSERT OR IGNORE INTO route_aliases (alias_route_id, canonical_route_id, notes) VALUES
    -- Scotland - Loch Loop (571 sightings as "Zwift Epic Race - Loch Loop")
    (742057576, 3019598975, 'Scotland - Loch Loop event variant'),
    
    -- Watopia - Danger Noodle (476 sightings as "HISP Spring Classics")
    (2888820995, 1993363743, 'Watopia - Danger Noodle event variant'),
    
    -- Watopia - Mountain 8 (262 sightings as "ZWC Hill Climb Battle")
    (3219074012, 2238254636, 'Watopia - Mountain 8 event variant'),
    
    -- Watopia - Sand And Sequoias (230 sightings as "Team DRAFT Monday Race")
    (604330868, 1109140215, 'Watopia - Sand And Sequoias event variant'),
    
    -- Watopia - Volcano Climb (220 sightings as "RollCo: Night Shift")
    -- Note: maps to "Volcano Climb After Party" which is the closest match
    (849508252, 387309391, 'Watopia - Volcano Climb event variant'),
    
    -- Watopia - Watopia''s Waistband (220 sightings as "MET-5 Race")
    (1064303857, 3896517838, 'Watopia - Waistband event variant'),
    
    -- London - Classique (210 sightings as "#EDDK Super Sunday Race")
    (2694166390, 170031640, 'London - Classique event variant'),
    
    -- Watopia - Figure 8 (180 sightings as "Team Not Pogi" event)
    -- Note: export says "Figure 8 Reverse" but closest DB match is "Figure 8"
    (553661379, 3137452716, 'Watopia - Figure 8 Reverse event variant'),
    
    -- Makuri Islands - Flatland Loop (104 sightings as "Sunday Masters Trilogy 2/3")
    (3282611437, 4256441024, 'Makuri Islands - Flatland Loop event variant'),
    
    -- Innsbruck - Innsbruckring (53 sightings as "Sunday Masters Trilogy 1/3")
    (2592027600, 1652556909, 'Innsbruck - Innsbruckring event variant'),
    
    -- Makuri Islands - Chain Chomper (10 sightings as "Ride Club Finland")
    (3691918883, 1801325388, 'Makuri Islands - Chain Chomper event variant');

-- Summary of aliases applied
SELECT 'Route aliases applied: ' || COUNT(*) || ' mappings' FROM route_aliases;

-- Show which unknown routes are now resolvable
SELECT 
    ur.event_name,
    ur.times_seen,
    r.name as resolved_route,
    r.distance_km
FROM unknown_routes ur
JOIN route_aliases ra ON ur.route_id = ra.alias_route_id
JOIN routes r ON ra.canonical_route_id = r.route_id
ORDER BY ur.times_seen DESC;
